/*layout should be root of app router so, every component could wrapped
layout does not re-render so, it stays like same which benefit for UI
we can define nested layout as well for variation of layout in different component
*/
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2>layout</h2>
        <div> {children}</div>
      </body>
    </html>
  );
}
