/*layout should be root of app router so, every component could wrapped
layout does not re-render so, it stays like same which benefit for UI
we can define nested layout as well for variation of layout in different component
*/
import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = [
    {
      href: "/",
      label: "Home",
    },
    { href: "/docs", label: "Docs" },
    { href: "/todos", label: "App" },
  ];
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <h2>layout</h2> */}
        {/* <div> {children}</div> */}
        <header>
          <nav>
            <ul className="flex item-center">
              {links.map((link) => (
                <li key={link.href}>
                  <Link href={link.href}>{link.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
